import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import './globals.css';
import SWRProvider from './swr-provider';

const notoSansKR = Noto_Sans_KR({
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={`${notoSansKR.className} overflow-x-hidden bg-background text-white`}>
        <SWRProvider>{children}</SWRProvider>
        <div id='modal-root'></div>
      </body>
    </html>
  );
}
